spring:
  application:
    name: ca-employee
  datasoruce:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: customer
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
    # Enabling H2 Console
    # Custom H2 Console URL
  h2:
    console.enabled: true
    console.path: /h2

  main:
    banner-mode: off
  messages:
    basename: i18n/messages

application-description: project.description
application-version: project.version
#    restart:
#      enabled: true
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    com.chstore.ca.employee: DEBUG
    com.chstore.ca.employee.review.client: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    root: ERROR
feign:
  hystrix:
    enabled: true